# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.90159381 0.91739962 0.66231569 ... 0.73679671 0.65190164 0.18734002]
 [0.40098113 0.58072565 0.09553054 ... 0.72265002 0.35726981 0.49925932]
 [0.39663205 0.66985293 0.06483241 ... 0.85668819 0.70050173 0.42838291]
 ...
 [0.59244091 0.62968351 0.38834385 ... 0.12320039 0.11230774 0.17660859]
 [0.34999233 0.64653991 0.2362199  ... 0.23771272 0.35164337 0.29664344]
 [0.13736523 0.41539543 0.23994537 ... 0.18422054 0.88191102 0.69030938]]
[[0.43084329 0.88222007 0.83742325 ... 0.35045883 0.53671973 0.26996322]
 [0.12710234 0.01793202 0.56677222 ... 0.25272671 0.75822227 0.5708704 ]
 [0.4295092  0.75205029 0.99421625 ... 0.51920423 0.92293706 0.15070387]
 ...
 [0.41777134 0.89289227 0.20447537 ... 0.15558144 0.87349953 0.4096414 ]
 [0.21581718 0.69724561 0.62851095 ... 0.48982571 0.43144732 0.00481982]
 [0.91294918 0.42357948 0.71680454 ... 0.77913201 0.16420636 0.14335115]]


Без использования numpy

In [17]:
def mult(a, b):
    result = None
    length = len(a)
    result = [[0 for i in range(length)] for i in range(length)]
    for i in range(length):
      for j in range(length):
        for k in range(length):
          result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [18]:
def np_mult(a, b):
    result = None
    result = a.dot(b)
    return result

In [19]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 693 ms, sys: 2.44 ms, total: 695 ms
Wall time: 697 ms


In [20]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.24 ms, sys: 1.93 ms, total: 3.18 ms
Wall time: 2.13 ms


In [21]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4651391211373266e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.58845822 0.36935804 0.03491262] [0.66598661 0.75131573 0.26298963]


In [58]:
def scalar_product(a,b):
    s = sum([a[i]*b[i] for i in range(len(a))])
    return s

In [60]:
def np_scalar_product(a,b):
    a = np.array(a)
    b = np.array(b)
    s = np.dot(a, b)
    return s

In [61]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 270 µs, sys: 50 µs, total: 320 µs
Wall time: 306 µs
CPU times: user 823 µs, sys: 936 µs, total: 1.76 ms
Wall time: 952 µs


18396.28406459235

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

** *Курсив*Ответ:** потому что numpy написан на C, засчет этого работает быстрее

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [53]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  d = a.diagonal()
  res = d[d % 2 == 0].sum()
  return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 4, 5, 1, 8],
       [3, 9, 9, 7, 1],
       [2, 8, 7, 4, 7],
       [7, 3, 6, 9, 8],
       [9, 2, 2, 7, 5]])

In [54]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 132 µs, sys: 23 µs, total: 155 µs
Wall time: 163 µs


0.0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [62]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = np.zeros_like(A)
    for i in range(len(A)):
        result[i, :] = np.cumsum(A[i])
    return result

In [63]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.95089265 0.33152397 0.7273314  0.11569741 0.81683797 0.54882585
 0.33277441 0.76327818 0.38185598 0.83012079 0.30995834 0.42537003
 0.95036361 0.5536979  0.66929294 0.28349343 0.69318242 0.08818427
 0.44329306 0.42277953 0.47806498 0.66538383 0.69377301 0.93725208
 0.24278381 0.74953711 0.60021193 0.92020218 0.46425955 0.57022367
 0.38352173 0.27902916 0.21510218 0.51793351 0.63999224 0.02226458
 0.31585325 0.84101413 0.06743898 0.48946848 0.88351626 0.92724267
 0.35844492 0.36046581 0.29603496 0.4848504  0.29416966 0.8555173
 0.22155752 0.77915175 0.754619   0.99707798 0.58453945 0.30561628
 0.35939671 0.57015378 0.98052267 0.00809408 0.29895274 0.34117418
 0.69726458 0.32432994 0.2356388  0.96849411 0.22747982 0.96930355
 0.21807407 0.08769677 0.35231142 0.28991608 0.9329988  0.08079972
 0.64864742 0.20723616 0.42598759 0.23463073 0.16219196 0.08352888
 0.04335111 0.25611085 0.2131469  0.19912892 0.24789208 0.36701607
 0.04399848 0.17894991 0.7333531  0.53240093 0.67020402 0.53170

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [64]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    ia = np.asarray(a)
    n = len(ia)
    if n == 0:
        return (None, None)
    else:
        y = np.array(ia[1:] != ia[:-1])
        i = np.append(np.where(y), n - 1)
        z = np.diff(np.append(-1, i))
        return(ia[i], z)

In [65]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 1.32 ms, sys: 58 µs, total: 1.38 ms
Wall time: 1.33 ms


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [71]:
# функция, решающая задачу с помощью NumPy
import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = []

    if len(X.shape) == 1:
        X = np.expand_dims(X, axis=0)

    for idx, arr in enumerate(X):
        Y = copy.deepcopy(arr)
        Y[1::2] = a
        Y[::2] = arr[::2]**3
        Y = Y[::-1]
        result.append(np.hstack((arr,Y)))

    return result

In [72]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 232 µs, sys: 0 ns, total: 232 µs
Wall time: 239 µs
